Global Alert - show the actual error message in the banner (#1019 #1028)
near/near-wallet pull request #1029
Opened 2020-10-14 22:40 UTC by marcinbodnar

2020-10-14 22:50 UTC, marcinbodnar commented
@kcole16 @ilblackdragon 
Wallet already has a functionality to show proper error in Global Alert banner - but the error from RPC need's to have a `type` property. For example, error, when there is a lack of storage balance to cover adding another 2FA confirmation, seems not to have `type`, so it's showing default error. 

With this change, all Global Alerts will also show the actual error message.

Ideally, all RPC errors should have a `type` property, and in Wallet, we should have all these types listed in translations files.

2020-10-16 17:30 UTC, marcinbodnar commented
@kcole16 @corwinharrell 
A new Global Alert is ready. I prepare it from scratch, so it's not using semantic ui anymore.

2020-10-16 17:47 UTC, corwinharrell commented
> it's not using semantic ui anymore

Praise god

2020-10-16 18:05 UTC, corwinharrell commented
@marcinbodnar this looks fantastic. Great job. 🚀

2020-10-16 18:05 UTC, corwinharrell approved these changes
@marcinbodnar this looks fantastic. Great job. 🚀

2020-10-16 18:45 UTC, Patrick1904 commented
Love this! Big improvement. Just a couple of thoughts:
1. After being redirected back to profile post recovery setup, the global alert only shows for ~0.5 
sec before disappearing (might be an existing issue). Can we fix that too?
2. Can we vertically align the global alert icon, it's just slightly off (please see attached)
3. Is there a reason for introducing a new font? (cc @corwinharrell). I am working on replacing our current font with one global font (Inter) [here](https://github.com/near/near-wallet/pull/1011)

![Screen Shot 2020-10-16 at 11 39 47 AM](https://user-images.githubusercontent.com/24921205/96296981-04d4af80-0fa5-11eb-91b0-4263ab2f4a4a.png)

2020-10-16 19:44 UTC, corwinharrell commented
@Patrick1904 The only new font is the one being used for the raw RPC output that I'd like to be monospace. Are we using a monospace typeface elsewhere? If so we can default to what we're already using.

2020-10-16 20:02 UTC, marcinbodnar commented
@Patrick1904 
> After being redirected back to profile post recovery setup, the global alert only shows for ~0.5
sec before disappearing (might be an existing issue). Can we fix that too?

What kind of recovery did you use?

> Can we vertically align the global alert icon, it's just slightly off (please see attached)

In this situation, when there is no text it looks off, but it looks good that way if there is a text. I wonder, what is the situation when only 'Success` header is displayed?

2020-10-16 20:05 UTC, corwinharrell requested changes
Just thought it would be nice for alerts lacking content to not have to be so small, so suggested the addition of a `min-width`.

2020-10-16 20:05 UTC, corwinharrell commented on src/components/responsive/GlobalAlert.js
> +    max-width: 500px;
Let's go ahead and add `min-width: 275px;`

2020-10-16 20:12 UTC, Patrick1904 commented
> @Patrick1904
> 
> > After being redirected back to profile post recovery setup, the global alert only shows for ~0.5
> > sec before disappearing (might be an existing issue). Can we fix that too?
> 
> What kind of recovery did you use?

Whenever I am logged in and start the recovery setup flow from the profile, and then get redirected back to the profile


> > Can we vertically align the global alert icon, it's just slightly off (please see attached)
> 
> In this situation, when there is no text it looks off, but it looks good that way if there is a text. I wonder, what is the situation when only 'Success` header is displayed?

I believe this was when I disabled seed phrase from the profile. Might want to align the icon vertically with the main heading/title (cc @corwinharrell)

2020-10-16 21:00 UTC, marcinbodnar commented
@Patrick1904 @corwinharrell 
Bug with disappearing alert after setting up recovery was not related to these changes. I fixed it for seed phrase, phone, and email.

Also adjusted Alert with only header visible.

2020-10-16 21:05 UTC, corwinharrell approved these changes

2020-10-19 16:44 UTC, Patrick1904 approved these changes

2020-10-19 16:44 UTC, merged