hotfix implicit accounts LAK/FAK and dup accountIds
near/near-wallet pull request #1071
Opened 2020-10-21 20:29 UTC by mattlockyer

2020-10-21 21:12 UTC, kcole16 commented
@mattlockyer Testing this locally, I still get the 2FA prompt when recovering with seed (for implicit account)

2020-10-21 21:14 UTC, mattlockyer commented
@kcole16 you will once, can't fix that unless we push to near-api-js

2020-10-21 21:42 UTC, kcole16 approved these changes

2020-10-22 04:24 UTC, vgrichina requested changes
Merged smaller hotfix, so let's figure out what are most desired long term changes

2020-10-27 23:50 UTC, merged