Redirect back to login screen after importing account
near/near-wallet pull request #1252
Opened 2020-12-02 16:19 UTC by mesquka

2020-12-02 23:30 UTC, vgrichina commented
@marcinbodnar I think you were doing some similar changes before, don't remember what's the latest on them

2020-12-03 00:14 UTC, marcinbodnar commented
@vgrichina yeah, I assume it's not about `importing` but `creating` account @mesquka ?

2020-12-03 00:27 UTC, mesquka commented
This change is specifically for `importing` accounts. The usecase is to allow users that are signing in on a new device to import accounts without abandoning the sign-in flow.

Adding the same flow to `createing` wallets probably makes sense as well, but the funding wallet step takes the user out of the sign-in flow so wasn't as high priority to me.

2020-12-03 00:44 UTC, marcinbodnar commented
@mesquka ok, but `EnableTwoFactor.js` is used only for creating account flow. Why changes to this component?

2020-12-03 00:56 UTC, marcinbodnar commented
@mesquka 
So it's already implemented for both creating and importing account and it should work well.
It's happening starting from here:
https://github.com/near/near-wallet/blob/master/src/components/Routing.js#L113
with `handleRefreshUrl`, `handleRedirectUrl ` and `handleClearUrl` actions.

The only thing that I can see is not working is skipping 2fa while creating an account.

2020-12-03 00:59 UTC, mesquka commented
> @mesquka ok, but `EnableTwoFactor.js` is used only for creating account flow. Why changes to this component?

Sorry, yep that's correct, was replying with outdated information (haven't had my morning coffee yet).

2020-12-03 01:00 UTC, mesquka commented
> @mesquka
> So it's already implemented for both creating and importing account and it should work well.
> It's happening starting from here:
> https://github.com/near/near-wallet/blob/master/src/components/Routing.js#L113
> with `handleRefreshUrl`, `handleRedirectUrl ` and `handleClearUrl` actions.
> 
> The only thing that I can see is not working is skipping 2fa while creating an account.

Redirecting after creating an account wasn't working, hence the changes.

2020-12-03 01:03 UTC, marcinbodnar requested changes

2020-12-03 01:03 UTC, marcinbodnar commented on src/components/accounts/two_factor/EnableTwoFactor.js
> +                    <FormButton className='link' onClick={() => skipUrl()}><Translate id='button.skip' /></FormButton>
In this case you just need use `dispatch(redirectToApp('/profile'))` it will redirect to `/login`

2020-12-03 01:03 UTC, marcinbodnar commented on src/components/login/Login.js
> +        this.props.history.push(`/create`)
these changes are unnecessary, it's been already done here:
https://github.com/near/near-wallet/blob/master/src/components/Routing.js#L113

2020-12-03 01:05 UTC, marcinbodnar commented
@mesquka 
> Redirecting after creating an account wasn't working, hence the changes.

Just tested with recovery seed phrase - seems to work well on testnet.

2020-12-03 01:08 UTC, marcinbodnar commented on src/components/accounts/two_factor/EnableTwoFactor.js
> +    const skipUrl = () => {
if you wanted to redirect back to App, the better idea would be to redirect to `/login` page - then the user is able to cancel the operation and will be redirected back to App.

2020-12-03 01:15 UTC, mesquka commented
Closing PR, will reopen later if needed.

2020-12-03 01:15 UTC, closed without merging