Transfer Fungible Tokens: prepare redux reducer
near/near-wallet pull request #1914
Opened 2021-07-13 18:39 UTC by marcinbodnar

Includes Redux `send` reducer, which handles actions related to transfer fungible tokens.

Transfers are stored in an array of objects, with similar structures for each transfer type.

2021-07-13 18:46 UTC, marcinbodnar commented
@MaximusHaximus 
There are few changes:
 - removed `dateTime` because function call doesn't return `block_timestamp` - we can generate it based on response time, but it wouldn't be accurate, and we actually don't need it as we would fetch for tx details to show receipt anyway
 - removed `details.token.name` and `details.token.symbol` because we would have to pass it as param to action, and we already store it in `token` reducer, so I guess we don't need to duplicate it.

2021-07-16 19:03 UTC, MaximusHaximus requested changes
Comments in-line!

I think maybe in the future it would make the most sense to _start_ with the PR that has the reducer logic + state, since how we structure the state and which selectors we provide drive the design of the rest of the system that uses that state.

2021-07-16 23:17 UTC, marcinbodnar commented on src/reducers/send/index.js
> +                        type: 'NEP141',
Sure, I was planning to import it from the action file, but the changes are not merged yet. But we can move it to the service file.

2021-07-16 23:38 UTC, marcinbodnar commented
> I think maybe in the future it would make the most sense to start with the PR that has the reducer logic + state, since how we structure the state and which selectors we provide drive the design of the rest of the system that uses that state.

Sure, I mean I'm still struggling a bit because in many cases I need to make changes in two PR simultaneously, also some bugs appear since I'm not able to test it all properly - but I still think it's a good idea to work like that, I think it will be better each time.

2021-07-16 23:41 UTC, marcinbodnar commented on src/reducers/send/index.js
> +                    ...state.items,
Sure I changed to one-and-only-one entry, but since we will be storing this data only when tx is submitted, we can store it all. 

Selector added.

2021-07-23 16:47 UTC, MaximusHaximus commented
> > I think maybe in the future it would make the most sense to start with the PR that has the reducer logic + state, since how we structure the state and which selectors we provide drive the design of the rest of the system that uses that state.
> 
> Sure, I mean I'm still struggling a bit because in many cases I need to make changes in two PR simultaneously, also some bugs appear since I'm not able to test it all properly - but I still think it's a good idea to work like that, I think it will be better each time.

Roger that -- I think the key thing is to make sure that any branches that build upon other un-merged branches are branched _off of the branch that they depend on_.

That way you can add commits to the 'parent' branch that this one depends on and then rebase this branch onto the branch which is its dependency.  This way way you can create individual branches with chunks of implementation, but still test the code in each branch against each-other.

The trick to make sure the diffs in the PRs are accurate is to make the target branch for any PR that depends on an un-merged branch to be that un-merged branch :). Happy to show you what this flow looks like via a hangout call :)

2021-07-23 16:47 UTC, MaximusHaximus commented
Closing this as we are not using redux state for the new send flow yet :)

2021-07-23 16:47 UTC, closed without merging

2021-07-27 22:31 UTC, marcinbodnar commented
> > > I think maybe in the future it would make the most sense to start with the PR that has the reducer logic + state, since how we structure the state and which selectors we provide drive the design of the rest of the system that uses that state.
> > 
> > 
> > Sure, I mean I'm still struggling a bit because in many cases I need to make changes in two PR simultaneously, also some bugs appear since I'm not able to test it all properly - but I still think it's a good idea to work like that, I think it will be better each time.
> 
> Roger that -- I think the key thing is to make sure that any branches that build upon other un-merged branches are branched _off of the branch that they depend on_.
> 
> That way you can add commits to the 'parent' branch that this one depends on and then rebase this branch onto the branch which is its dependency. This way way you can create individual branches with chunks of implementation, but still test the code in each branch against each-other.
> 
> The trick to make sure the diffs in the PRs are accurate is to make the target branch for any PR that depends on an un-merged branch to be that un-merged branch :). Happy to show you what this flow looks like via a hangout call :)

Thanks for the explanation, I think I know what you mean, but I will get back to you with this when there will be a similar situation.