Revamp 'available balance'
near/near-wallet pull request #2076
Opened 2021-08-31 21:43 UTC by Patrick1904

2021-09-01 17:19 UTC, MaximusHaximus requested changes
Looks awesome, just two things :+1:

2021-09-01 20:42 UTC, Patrick1904 commented on packages/frontend/src/reducers/selectors/balance.js
> +        reservedForTransactions: new BN(available).sub(new BN(parseNearAmount(WALLET_APP_MIN_AMOUNT))).isNeg()
Good point :)

2021-09-01 22:58 UTC, corwinharrell requested changes
Just a couple small things:

1. Let's make sure the styling of the staking section matches the one above (indentation + gray background)

<img width="614" alt="Screen Shot 2021-09-01 at 6 53 26 PM" src="https://user-images.githubusercontent.com/5934188/131755952-42e08517-3733-453f-bbbd-7056c8cdb6a7.png">

2. @MaximusHaximus made a good suggestion to keep the tooltip on the available balance, and to also include a text link that points to the account details page, just so it makes the transition a little easier. I think new can change the available balance text to:

> Your spendable NEAR balance excluding funds locked or staked. _View Balance Breakdown_ →

2021-09-02 00:13 UTC, corwinharrell commented
Not at my computer for the rest of the night to review again so feel free to merge after those changes 👍

2021-09-02 00:27 UTC, merged