E2e ci localserver
near/near-wallet pull request #2174
Opened 2021-09-30 17:23 UTC by esaminu

Added functionality to bundle code in docker container and serve the code locally before running the e2e tests.

2021-12-15 20:07 UTC, MaximusHaximus requested changes
:D <3 :) Comments inline

2021-12-15 20:07 UTC, MaximusHaximus commented on packages/e2e-tests/utils/SelfReloadingJSONRpcProvider.js
> +class SelfReloadingJSONRpcProvider extends JsonRpcProvider {
Per offline conversation, let's make sure we cache the pending promise for `reloadAccount()` and chain on it if we are performing multiple parallel requests, chain on the existing pending reload request

2022-01-11 11:57 UTC, MaximusHaximus approved these changes
This is ready to rock -- **but it looks like we've got some changes in this changeset that shouldn't be there**.

Once we've got #2299 landed, please rebase this on `master` and double-check that these are no longer showing as diffs.

2022-01-12 19:36 UTC, esaminu commented on packages/e2e-tests/playwright.config.js
> +            "cd ../frontend && npx serve dist -l 1234 -s --ssl-cert devServerCertificates/primary.crt --ssl-key devServerCertificates/private.pem",
I'll do this in a follow up PR 👍

2022-01-12 19:40 UTC, esaminu commented
> This is ready to rock -- **but it looks like we've got some changes in this changeset that shouldn't be there**.

Rebased and the changes are no longer on this changeset! 👍

2022-01-12 19:41 UTC, merged