Create account w/ initial deposit: handle error
near/near-wallet pull request #2253
Opened 2021-11-16 23:22 UTC by Patrick1904

2021-11-16 23:26 UTC, Patrick1904 commented
@MaximusHaximus I added similar error handling to account creation with initial deposit as we added for [coin op](https://github.com/near/near-wallet/pull/2237). PTAL when you have a chance.

2021-11-22 21:44 UTC, MaximusHaximus requested changes
:+1: Just one question about not using `dispatch()` for the `redirectTo` action

2021-11-22 21:44 UTC, MaximusHaximus commented on packages/frontend/src/components/accounts/create/initial_deposit/InitialDepositWrapper.js
> +                    redirectTo('/recover-account');
Should this be using a `dispatch()`?

2021-11-22 21:51 UTC, Patrick1904 commented on packages/frontend/src/components/accounts/create/initial_deposit/InitialDepositWrapper.js
> +                    redirectTo('/recover-account');
Great catch:)

2021-11-22 22:34 UTC, merged