feat: added additional permission to LAK login display
near/near-wallet pull request #2572
Opened 2022-04-06 19:39 UTC by esaminu

This PR adresses concerns in and closes #2567 :
* Adds a new permission display regarding the ability to call methods on the contract

<img width="300" alt="image" src="https://user-images.githubusercontent.com/5849204/162056108-e44ce358-1706-4813-96c2-2def5ebae494.png">

2022-04-06 20:58 UTC, Patrick1904 requested changes
Thanks for addressing this! I'm getting a weird UI bug in Chrome, but you can fix that by adding `min-width: 32px` in [PermissionItem.js](https://github.com/near/near-wallet/blob/master/packages/frontend/src/components/login/v2/PermissionItem.js#L13)

<img width="567" alt="Screen Shot 2022-04-06 at 1 56 25 PM" src="https://user-images.githubusercontent.com/24921205/162069332-0658c28a-8602-4e2f-a466-e456fbd3a2dd.png">

2022-04-06 22:10 UTC, corwinharrell commented
I would also encourage us to always try to think of articulating these types of things in layman's terms, so that the messaging is valuable to non-developers. How might this permission be framed in such a way that doesn't depend on prerequisite knowledge about smart contracts and programing?

2022-04-07 20:53 UTC, esaminu commented
Thanks for catching @Patrick1904 ! Updated 😄

2022-04-11 22:02 UTC, Patrick1904 approved these changes
Thanks @esaminu! I'm merging this. Let's update the copy in a follow-up if needed.

2022-04-11 22:02 UTC, merged