feat: added functionality "Donate to Ukraine"
near/near-wallet pull request #2593
Opened 2022-04-22 11:34 UTC by OlegYak

This is a PR to add the ability to donate to Ukraine
![Screenshot from 2022-04-22 14-16-20](https://user-images.githubusercontent.com/101889013/164706801-6c5ec454-6351-4ce5-8201-68fcd0a1e596.png)
.

2022-05-05 22:10 UTC, agileurbanite requested changes
Overall, I am curious why this PR is so verbose?  Can't we just have a button that sets the state of the component for sender input to the ukraine address?  I feel like this PR introduces unnecessary complexity.

2022-05-05 22:10 UTC, agileurbanite commented on packages/frontend/src/components/DonateToUkraine/DonateContainer.js
> +            handleSendToken={async (rawAmount, receiverId, contractName) => {
nit inline anon functions can be abstracted so we can see common patterns and create reusable abstractions.  This encourages modular code that is easier to test.

2022-05-05 22:10 UTC, agileurbanite commented on packages/frontend/src/components/DonateToUkraine/DonateContainerV2.js
> +        let targetToken = fungibleTokens.find(({ contractName }) =>
nit: this is hard to read imo might be worth it to break out into a common function as both sides of this Maybe are 80% the same.

2022-05-05 22:10 UTC, agileurbanite commented on packages/frontend/src/components/svg/SwapIconTwoArrows copy.js
> +<<<<<<< HEAD
remove these merge conflict commits

2022-05-05 22:10 UTC, agileurbanite commented on packages/frontend/src/components/svg/SwapIconTwoArrows copy.js
> +=======
remove these merge conflict commits

2022-05-05 22:10 UTC, agileurbanite commented on packages/frontend/src/components/svg/SwapIconTwoArrows copy.js
> +<<<<<<< HEAD
remove these merge conflict commits

2022-05-05 22:10 UTC, agileurbanite commented on packages/frontend/src/components/wallet/TokenBox.js
> +// const FRAC_DIGITS = 5;
why comment, just remove it.

2022-05-05 22:32 UTC, morgsmccauley commented
Agree with @agileurbanite here

I don't think we need to add an entire new set of components and route for something that's already very similar to what we have. We have the capability for deep-linking to send tokens to a specific account, let's just utilise that.

I'd suggest we keep `NavLink.js` as it is, i.e. show the "Donate to Ukraine" link in the header, but instead route to `/send-money/ukraine` (where `ukraine` is the accountId). Then we can remove `/donate-to-ukraine` and related code.

This does add an additional step compared to this flow - confirming the receiver ID, but this will be pre-populated with `ukraine` as it's pulled from the URL. This is a bit more work for users but is probably more familiar since it's what they're used to.

2022-05-06 17:47 UTC, agileurbanite commented
Closing as duplicate of #2639

2022-05-06 17:47 UTC, closed without merging