feat: FIFS-174 Wrap/Unwrap
near/near-wallet pull request #2621
Opened 2022-04-28 09:04 UTC by SerDorosh

https://nearinc.atlassian.net/browse/FIFS-174

2022-05-02 16:56 UTC, agileurbanite commented
@SerDorosh we won't block this PR unless it introduces serious bugs but @gutsyphilip will leave a bunch of comments just for best practices

2022-05-02 23:58 UTC, gutsyphilip requested changes
Looks good overall. Amazing work!
Just requested a couple of changes to adhere to best practices and our standards.

2022-05-02 23:58 UTC, gutsyphilip commented on packages/frontend/src/components/wrap/SwapNear.js
> +                );
We should extract this into it's own function.

2022-05-02 23:58 UTC, gutsyphilip commented on packages/frontend/src/components/wrap/components/SwapAmountForm.js
> +                        }}
Extract to named function.

2022-05-02 23:58 UTC, gutsyphilip commented on packages/frontend/src/components/wrap/components/helper.js
> +            numToShow: '0',
These utils should be moved to `src/utils/wrap-unwrap.js`

2022-05-03 10:29 UTC, SerDorosh commented
Thanks!
Done.

2022-05-03 12:09 UTC, gutsyphilip approved these changes
Nice work. Thanks for making the updates. 
Made some UI updates based on the design. 
I'll go ahead and approve this now.

2022-05-03 15:33 UTC, merged