feat: add copy button to address list
near/near-wallet pull request #2682
Opened 2022-05-18 06:51 UTC by 1bitl

Adds a "Copy to clipboard" button to the accounts list.

This required a nudge on the "Copied" text so that it doesn't cut off by the surrounding list.
Also changes the tooltip text to a description of what the button does.

Fixes https://github.com/near/near-wallet/issues/2620

<img width="325" alt="image" src="https://user-images.githubusercontent.com/94780425/168972090-ed768dfb-de73-4022-a0c7-4fb1b9627e09.png">

<img width="493" alt="image" src="https://user-images.githubusercontent.com/94780425/168972571-7e96f4b4-babd-486a-acbf-154d6f69f706.png">

2022-05-18 17:26 UTC, Patrick1904 requested changes
Thanks for the PR @1bitl! I noticed that when you click on the copy button on an account other than the current account in the dropdown, the copy button does not work and the menu closes on click. Can you please look into that?

2022-05-19 05:07 UTC, 1bitl commented
@Patrick1904 Thanks for the quick review, and nice catch! Fixed and added an event to the `ClickToCopy` component.

2022-05-23 20:33 UTC, Patrick1904 commented
@1bitl the issue still persists for me while testing - basically no copy and the dropdown closes.

I'm also noticing that the success toast for the `ClickToCopy` component gets cut off at the top - can we please avoid style changes to the `ClickToCopy` component?

<img width="142" alt="Screen Shot 2022-05-23 at 1 33 03 PM" src="https://user-images.githubusercontent.com/24921205/169901285-ee43b8b1-430a-4b21-be3d-03210d2c642a.png">

2022-06-07 14:08 UTC, Patrick1904 commented
Great job @1bitl - it works well now! 👍

2022-06-07 14:08 UTC, Patrick1904 approved these changes
Great job @1bitl - it works well now! 👍

2022-06-07 14:09 UTC, merged