feat: add batch export to ledger wallet route
near/near-wallet pull request #2778
Opened 2022-06-23 21:48 UTC by esaminu

This PR adds a batch export route to ledger wallet at `/batch-ledger-export` per [KWLT-24](https://nearinc.atlassian.net/browse/KWLT-24). It supports adding all non ledger accounts (phrase / 2fa) as ledger accounts which allows the user to use the ledger directly from a dapp or via the [wallet-selector](https://github.com/near/wallet-selector)

2022-06-25 00:27 UTC, andy-haynes requested changes
Looking good, comments inline.

I am having an issue where I export a new account (phrase):
- have ledger disconnected
- go to export link
- export account to ledger, including connecting the ledger
- successfully export ledger
- navigate to `/profile`
-  ledger shows disconnected (`Your ledger is not currently connected...`)
- try to connect

When I try to connect the ledger I get a modal prompting me to confirm adding a key but I never get a prompt on the ledger. From here the UI seems to prevent me from ever connecting the ledger. Is this a known bug or is something wrong with the app state at this point?

2022-06-27 16:31 UTC, esaminu commented
Thanks for testing @andy-haynes 💖 . This is actually due to [this change](https://github.com/near/near-wallet/pull/2778/files#diff-a0e3f69e49001fdea1c6d17e5f105395f9e83a9a7b7be6a6d6a3899ab2e7a9d0L204-R205) from `localKey.permission` to `localKey.access_key.permission` since the `AccessKeyInfoView` type [returned by `getAccessKeys`](https://github.com/near/near-api-js/blob/master/src/account.ts#L596) does not have a `permission` field. It seems there's logic around the app that relies on [`getLegerKey`](https://github.com/near/near-wallet/pull/2778/files#diff-a0e3f69e49001fdea1c6d17e5f105395f9e83a9a7b7be6a6d6a3899ab2e7a9d0R191) returning a key even if we have a FAK in the localStorage keystore though so changed it back for now. In practice this means that the user will be prompted to sign transactions with a ledger even if we have a FAK in localStorage and the FAK will be ignored. You can recreate this state by going to `https://wallet.testnet.near.org/setup-ledger/${accountId}` and selecting "Keep existing keys" at the end. cc @MaximusHaximus 

Great catch! 🙂

2022-06-27 16:41 UTC, esaminu commented on packages/frontend/src/components/accounts/batch_ledger_export/index.js
> +    const [, setLedgerAccounts] = useState([]);
The idea is to render something like "Accounts already in Ledger" or similar on a following iteration

2022-06-27 16:46 UTC, esaminu commented on packages/frontend/src/components/accounts/batch_ledger_export/AccountExportModal.js
> +                                !account.keyType || account.keyType === WalletClass.KEY_TYPES.OTHER || account.keyType === WalletClass.KEY_TYPES.LEDGER
So this condition will return `true` if `account.keyType` is falsy or if it's `OTHER` or `LEDGER`. With short circuit evaluation the other two operands will not be evaluated unless `account.keyType` has a value.

2022-06-27 16:56 UTC, esaminu commented on packages/frontend/src/utils/wallet.js
> +        const accountHasLedgerKey = accessKeys.map((key) => key.public_key).includes(ledgerPublicKey.toString());
Was hesitant to change the old copied code for this but updated both `addLedgerAccessKey` and  `exportToLedgerWallet`

2022-06-27 17:08 UTC, esaminu commented on packages/frontend/src/components/accounts/batch_ledger_export/AccountExportModal.js
> +    }, [onSuccess, account.accountId, ledgerConnectionAvailable]);
Updated thanks for catching that!

2022-06-27 18:10 UTC, andy-haynes commented
> In practice this means that the user will be prompted to sign transactions with a ledger even if we have a FAK in localStorage and the FAK will be ignored.

I tested this a bit and didn't see any differences with how it currently works on testnet. My steps are:
- create account with phrase (from testnet preview link on this PR)
- export to ledger with the new route added in this PR
- clear localstorage
- import account

If I import with the phrase, I can still sign transactions without ledger. If I recover with ledger instead, I'm forced to sign with ledger.

So it looks fine to me, let me know if there's something else I should be testing for specifically.

2022-06-27 18:51 UTC, esaminu commented
The case I’m talking about is:

1. Go to `https://wallet.testnet.near.org/setup-ledger/${accountId}` with an existing phrase accountId on testnet
2. Setup ledger for the account
3. After this completes you will be prompted to either Remove or keep existing keys
4. Choose “Keep existing keys”
5. Attempt to send a transaction.

You will be prompted to sign the transaction with your ledger even though we have a FAK in local storage (It wasn’t removed when you setup ledger).

I don't think removing the option to keep your FAK (removing it without prompting the user) when enabling ledger is a good solution but I think we can have a better UI state than (Your ledger is not currently connected...) that was visible earlier and also I think we can sign transactions with a FAK instead of ledger when we have one since it's better UX. For now the behavior in this PR is unchanged from testnet and I'll file an issue so that this can be discussed further. 👍

2022-06-27 18:59 UTC, andy-haynes approved these changes

2022-06-27 19:11 UTC, merged