feat: made Sentry lazy
near/near-wallet pull request #2785
Opened 2022-06-28 11:55 UTC by followdarko

This reverted commit 7b24611caa04513a30e9f1f7a5d688dbecc461f4 highlighted the problem that when main js bundle has an errror than sentry will not initialize and we don't see the problem. This PR moves Sentry to separate script that loads before the main bundle. This is the lightweight sentry lazy skeleton around main sentry SDK. For now this PR isn't completed because I don't have access to Senty web interface to get Setry_client_key. Someone who have access should pass the key into bundle. Then me or someone else could continue work and test this PR.

2022-06-28 11:56 UTC, followdarko commented on packages/frontend/src/redux/actions/staking.js
> +import { fungibleTokensService } from '../../services/FungibleTokens';
Random error in current master that prevents `yarn run commit` =/

2022-08-11 20:46 UTC, MaximusHaximus commented
1. It's worth noting that this now loads a version of Sentry that we may have never run any tests against (or even loaded in our UI previously) because it is loading from a CDN which will be swapped out without announcement; by using `@sentry/browser` directly, we ensure that the version of Sentry we are running does not change without us explicitly bumping its version (which is also desirable from a security standpoint, as it reduces our risk of pulling in a supply chain attack in a just-published release of the dependency).
2. How does the app behave if the script tag fails to load? e.g. I block the CDN that the lazy-loader tries to load Sentry from?

2022-08-12 16:35 UTC, roshaans requested changes

2022-08-12 16:35 UTC, roshaans commented on packages/frontend/src/utils/sentryLazy.js
> +  window.__SENTRY_CLIENT_KEY__ || '', // TODO: need to pass Sentry client key
I believe you should be able to get the Sentry_DSN similarly to the [following](https://github.com/near/near-wallet/blob/4582f61fd49d2337cc33d267b53594b733185098/packages/frontend/src/utils/sentry.js)

2022-08-30 12:47 UTC, followdarko commented
I will return to this after Nearcon

2023-02-09 22:48 UTC, closed without merging