Mynw 108 fix risk scoring bug
near/near-wallet pull request #2849
Opened 2022-07-26 19:14 UTC by PinkiNice

This PR:
* Fixes bug with disabled button on `Send Screen` on validated account
* Makes `Send Screen` waits on risk-score result before allowing to proceed (reduces flickering)
* Adds state reset for risk-score hook between checks for different accounts
* Fixes bug with checkbox losing state between checks

2022-07-26 19:22 UTC, Patrick1904 approved these changes
LGTM. Thanks for the quick fix @PinkiNice!

2022-07-26 19:24 UTC, Patrick1904 requested changes
For some reason, it seems implicit accounts are still stuck at this step? Can we fix that?

2022-07-27 11:02 UTC, followdarko commented
@PinkiNice take a look at this draft https://github.com/near/near-wallet/pull/2852, if everything ok please merge it here

2022-07-27 11:07 UTC, followdarko commented
@Patrick1904 this UI/UX with implicit accounts  is not intuitive clear. Probably it is better to still mark it green or at least show some notification to user?

2022-07-27 15:46 UTC, followdarko commented
We could also https://github.com/near/near-wallet/pull/2853 merge it here

2022-07-27 16:03 UTC, agileurbanite commented
Where are we with this PR @PinkiNice ? it looks like there's a few conflicts and not sure if #2853 is still necessary given #2852 was merged.  Am I right to assume this @followdarko ? @Patrick1904 as FYI

2022-07-27 16:37 UTC, Patrick1904 commented
@followdarko can we please add these changes into a PR for https://github.com/near/near-wallet/pull/2840 so that we can test it all together before we merge?

2022-08-03 18:01 UTC, closed without merging