MYNW-121-fix-account-id-overflow-for-nft-modal
near/near-wallet pull request #2896
Opened 2022-09-01 09:09 UTC by NotEternal

Task: 
https://mnw.atlassian.net/browse/MYNW-121

Preview (attention on the receiver ID):
https://www.loom.com/share/27e6b26527064e1caecbc8e3ca5bb89d
or
https://user-images.githubusercontent.com/61930014/187254485-101716d2-cc79-4efb-9857-fce5b5766c6c.mp4

Changes:
- created a new function to shorten implicit accoun IDs
- IDs in the NFT transfer modal were wrapped with it

2022-09-01 17:09 UTC, Patrick1904 commented on packages/frontend/src/utils/account.test.js
> +test('It should shorten account ID with correct format', () => {
Thanks for adding tests 🙏

2022-09-01 17:13 UTC, Patrick1904 approved these changes
LGTM 👍 

@NotEternal there are quite a few other places in the wallet where ellipsis treatment would be nice - sending fungible tokens, etc. It'd be great if you created a follow-up PR to change this in the remaining places too.

2022-09-01 17:44 UTC, Patrick1904 commented on packages/frontend/src/utils/account.js
> +    const isPartMissing = startChars < 1 || endChars < 1;
Can we rename this to `invalidCharCount`?

2022-09-01 17:44 UTC, NotEternal commented
> LGTM +1
> 
> @NotEternal there are quite a few other places in the wallet where ellipsis treatment would be nice - sending fungible tokens, etc. It'd be great if you created a follow-up PR to change this in the remaining places too.

I'll look at those places while learning codebase and add them in a new issue

2022-09-01 17:51 UTC, roshaans requested changes
Nice job! :) Just a few nit picky things to change.

2022-09-01 17:51 UTC, roshaans commented on packages/frontend/src/utils/constants.js
> +export const IMPLICINT_ACCOUNT_MAX_LENGTH = 64;
nit: spelling mistake -> `IMPLICINT` -> `IMPLICIT`

2022-09-01 17:51 UTC, roshaans commented on packages/frontend/src/utils/account.test.js
> +
Rename file to be something more specific like shortenAccountId.test.js

2022-09-02 09:54 UTC, roshaans approved these changes
Nice job :) 

It will be nice in later PRs as @Patrick1904 mentioned to introduce this to different parts of the app.  LGTM!

2022-09-02 09:54 UTC, roshaans commented on packages/frontend/src/utils/constants.js
> +export const IMPLICIT_ACCOUNT_MAX_LENGTH = 64;
Nit: Change name from `IMPLICIT_ACCOUNT_MAX_LENGTH` -> `IMPLICIT_ACCOUNT_LENGTH`

2022-09-02 09:55 UTC, merged