Replacing Segment to RudderStack on transfer wizard metrics
near/near-wallet pull request #3067
Opened 2023-06-19 05:00 UTC by hcho112

This PR contains changes from replacing Segment to Rudderstack. 

Currently these metrics are only active within wallet transfer functionality.

2023-06-19 14:20 UTC, roshaans commented on packages/frontend/src/components/wallet-migration/metrics.js
> +            : '2RPBBhH1Dka2bYG6HKQmvkzNUdz';
@pkudinov Will we have a separate key for mainnet/testnet?

2023-06-19 15:32 UTC, roshaans approved these changes
Nice job! Overall looks good. Just some minor changes in naming...

I tested the code in the browser and it seems to forward the events as expected!

2023-06-19 15:32 UTC, roshaans commented on packages/frontend/src/components/wallet-migration/metrics.js
> +    return rudderanalytics.reset();
`rudder-stack-js` does not expose a publicly available method similar to the functionality of `segment.flush()` which is intended for forcing all queued events to be sent immediately to the server. `.reset()` does not do that here though.

 It simply resets the anonymousId as well as the userAccountId that we are tracking as per the implementation [here](https://github.com/rudderlabs/rudder-sdk-js/blob/66c998ba2785cd33445119f9468d0d3488b34f38/src/core/analytics.js#L1071).
 
I think we can rename this method to `resetUserState()` instead.

2023-06-19 15:38 UTC, roshaans requested changes

2023-06-19 15:38 UTC, roshaans commented on packages/frontend/src/components/wallet-migration/WalletMigration.jsx
> +        flushEvents();
At the moment, when `flushEvents()` gets called we will have descrepencies in our data as `flushEvents()` calls `rudderStack.reset()` which will reset the current logged in user data. We should remove flushEvents() here.

2023-06-19 22:46 UTC, hcho112 commented
@roshaans thank you for thoughtful review!

2023-06-22 05:09 UTC, hcho112 commented
I have rebased master. This PR needs to be reviewed & merged prior to releasing transfer wizard, so would be appreciated if I can get more reviews

2023-06-22 19:33 UTC, andy-haynes approved these changes
LGTM 👍

2023-06-22 20:53 UTC, merged